---
name: Valores y Funciones
locale: es
type: learning
beta: true
teacher_info: ''
language: haskell
id_format: "%05d"
order:
- 100
- 200
- 300
- 400
- 500
- 600
- 650
- 675
- 700
- 800
- 1101
- 1100
